# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MER.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#ZKOUŠKA

from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import filedialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.central = QtWidgets.QWidget(MainWindow)
        self.central.setObjectName("central")
        self.akce = QtWidgets.QPushButton(self.central)
        self.akce.setGeometry(QtCore.QRect(50, 500, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.akce.setFont(font)
        self.akce.setObjectName("akce")
        self.pridat = QtWidgets.QPushButton(self.central)
        self.pridat.setGeometry(QtCore.QRect(192, 500, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pridat.setFont(font)
        self.pridat.setObjectName("pridat")
        self.graf = QtWidgets.QPushButton(self.central)
        self.graf.setGeometry(QtCore.QRect(320, 500, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graf.setFont(font)
        self.graf.setObjectName("graf")
        self.exp = QtWidgets.QPushButton(self.central)
        self.exp.setGeometry(QtCore.QRect(470, 500, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exp.setFont(font)
        self.exp.setObjectName("exp")
        self.table = QtWidgets.QTableWidget(self.central)
        self.table.setGeometry(QtCore.QRect(50, 90, 691, 391))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.souradnice = QtWidgets.QPushButton(self.central)
        self.souradnice.setGeometry(QtCore.QRect(620, 500, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.souradnice.setFont(font)
        self.souradnice.setObjectName("souradnice")
        self.fix_label = QtWidgets.QLabel(self.central)
        self.fix_label.setGeometry(QtCore.QRect(40, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fix_label.setFont(font)
        self.fix_label.setObjectName("fix_label")
        self.nazev_akce = QtWidgets.QLabel(self.central)
        self.nazev_akce.setGeometry(QtCore.QRect(180, 20, 561, 41))
        self.nazev_akce.setText("")
        self.nazev_akce.setObjectName("nazev_akce")
        MainWindow.setCentralWidget(self.central)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.akce.setText(_translate("MainWindow", "Výběr akce"))
        self.pridat.setText(_translate("MainWindow", "Přidat data"))
        self.graf.setText(_translate("MainWindow", "Graf"))
        self.exp.setText(_translate("MainWindow", "Export"))
        self.souradnice.setText(_translate("MainWindow", "Souřadnice"))
        self.fix_label.setText(_translate("MainWindow", "NÁZEV:"))

class OpenWindowAddMeas:
    def OpenFile(OpenFile):
        file = filedialog.askopenfilename(
            initialdir="C:/Users",
            title="Otevřit soubor",
            filetypes=(("Soubor", "*.txt"),)
        )
        return OpenFile = open(str(file), 'r')